name: Publish EcoLPR API

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build and Publish with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publish
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.ECOLPR_API_PUBLISH_TOKEN }}

