name: Publish EcoLPR API

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout latest code
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3.14.1
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Publish api
        uses: gradle/actions@v4.4.0
        with:
          arguments: publish
        env:
          MAVEN_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ECOLPR_API_PUBLISH_TOKEN }}
